#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_clair="0.0.1"
  jq -n --arg clair "$ver_clair" '{clair: $clair}'
}

version "$@"
